// examples/selectors-vue/src/components/Counter.vue
<script setup lang="ts">
import { ref } from "vue";

const props = defineProps<{
  step?: number;
}>();

const count = ref(0);
</script>

<template>
  <div class="counter">
    <button @click="count -= props.step ?? 1">-</button>
    <span>{{ count }}</span>
    <button @click="count += props.step ?? 1">+</button>
  </div>
</template>

// packages/selectors-react/examples/src/components/Counter.tsx
import { useState } from "react";

interface CounterProps {
  step?: number;
}

export function Counter({ step = 1 }: CounterProps) {
  const [count, setCount] = useState(0);

  return (
    <div className="counter">
      <button onClick={() => setCount((c) => c - step)}>-</button>
      <span data-testid="count">{count}</span>
      <button onClick={() => setCount((c) => c + step)}>+</button>
    </div>
  );
}
