// packages/selectors-react/examples/src/components/Counter.tsx
import { useState } from "react";

interface CounterProps {
  step?: number;
}

export function Counter({ step = 1 }: CounterProps) {
  const [count, setCount] = useState(0);

  return (
    <div className="counter">
      <button onClick={() => setCount((c) => c - step)}>-</button>
      <span data-testid="count">{count}</span>
      <button onClick={() => setCount((c) => c + step)}>+</button>
    </div>
  );
}

// examples/selectors-angular/src/app/components/counter/counter.component.ts
import { Component, Input, signal } from '@angular/core';

@Component({
  selector: 'app-counter',
  standalone: true,
  template: `
    <div>
      <button (click)="decrement()">-</button>
      <span data-testid="count">{{ count() }}</span>
      <button (click)="increment()">+</button>
    </div>
  `,
})
export class CounterComponent {
  @Input() step = 1;
  count = signal(0);

  increment(): void {
    this.count.update((c) => c + this.step);
  }

  decrement(): void {
    this.count.update((c) => c - this.step);
  }
}
